package hello

import (
	"connectrpc.com/connect"
	"context"
	"encore.dev/rlog"
	"fmt"
	hellov1 "github.com/sunit-kulkarni/encore-connect/gen/hello/v1" // generated by protoc-gen-go
	"github.com/sunit-kulkarni/encore-connect/hello/workflow"
	"go.temporal.io/sdk/client"
)

type Server struct {
	client client.Client
}

func (s *Server) Hello(
	ctx context.Context,
	req *connect.Request[hellov1.HelloRequest],
) (*connect.Response[hellov1.HelloResponse], error) {
	options := client.StartWorkflowOptions{
		ID:        "greeting-workflow",
		TaskQueue: greetingTaskQueue,
	}
	we, err := s.client.ExecuteWorkflow(ctx, options, workflow.Greeting, req.Msg.Name)
	if err != nil {
		return nil, err
	}
	rlog.Info("started workflow", "id", we.GetID(), "run_id", we.GetRunID())

	// Get the results
	var greeting string
	err = we.Get(ctx, &greeting)
	if err != nil {
		return nil, err
	}
	res := connect.NewResponse(&hellov1.HelloResponse{
		Greeting: fmt.Sprintf("Temporal says the following: %s!", greeting),
	})
	res.Header().Set("Hello-Version", "v1")
	return res, nil
}
